"""add_exam_model

Revision ID: 004330bbeb51
Revises: c4a0adaa4ce8
Create Date: 2026-07-02 09:39:27.522119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004330bbeb51'
down_revision = 'c4a0adaa4ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('very_complex_percentage', sa.Integer(), nullable=False),
    sa.Column('complex_percentage', sa.Integer(), nullable=False),
    sa.Column('medium_percentage', sa.Integer(), nullable=False),
    sa.Column('easy_percentage', sa.Integer(), nullable=False),
    sa.Column('exam_duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'exams', ['exam_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exam_id')

    op.drop_table('exams')
    # ### end Alembic commands ###
