"""add_difficulty_distribution_toggle

Revision ID: 0d2e9b036170
Revises: 004330bbeb51
Create Date: 2026-07-03 19:01:21.512958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2e9b036170'
down_revision = '004330bbeb51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_difficulty_distribution', sa.Boolean(), nullable=True))

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_difficulty_distribution', sa.Boolean(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE exam_configurations SET use_difficulty_distribution = TRUE")
    op.execute("UPDATE exams SET use_difficulty_distribution = TRUE")

    # Alter columns to be NOT NULL
    with op.batch_alter_table('exam_configurations', schema=None) as batch_op:
        batch_op.alter_column('use_difficulty_distribution', nullable=False)

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.alter_column('use_difficulty_distribution', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('use_difficulty_distribution')

    with op.batch_alter_table('exam_configurations', schema=None) as batch_op:
        batch_op.drop_column('use_difficulty_distribution')

    # ### end Alembic commands ###
