"""drop_difficulty_level_column

Revision ID: 38b8a72e31ad
Revises: 0d2e9b036170
Create Date: 2026-07-04 17:27:41.319686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b8a72e31ad'
down_revision = '0d2e9b036170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('difficulty_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
