"""add_exam_patterns_and_float_score

Revision ID: 5dc72e38f6cb
Revises: 38b8a72e31ad
Create Date: 2026-07-04 18:14:00.029673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc72e38f6cb'
down_revision = '38b8a72e31ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('exam_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pattern', sa.String(length=20), nullable=False, server_default='HR'))

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pattern', sa.String(length=20), nullable=False, server_default='HR'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('pattern')

    with op.batch_alter_table('exam_configurations', schema=None) as batch_op:
        batch_op.drop_column('pattern')

    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
