"""add_passing_marks_and_threshold

Revision ID: 8b41720afeb2
Revises: 5dc72e38f6cb
Create Date: 2026-07-04 19:05:08.524506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b41720afeb2'
down_revision = '5dc72e38f6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passing_marks', sa.Float(), nullable=False, server_default='4.0'))
        batch_op.add_column(sa.Column('override_threshold', sa.Float(), nullable=False, server_default='3.0'))

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passing_marks', sa.Float(), nullable=False, server_default='4.0'))
        batch_op.add_column(sa.Column('override_threshold', sa.Float(), nullable=False, server_default='3.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('override_threshold')
        batch_op.drop_column('passing_marks')

    with op.batch_alter_table('exam_configurations', schema=None) as batch_op:
        batch_op.drop_column('override_threshold')
        batch_op.drop_column('passing_marks')

    # ### end Alembic commands ###
